name: Deploy Vite App to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # リポジトリのクローン
      - name: Checkout the repository
        uses: actions/checkout@v3

      # Node.js のセットアップ
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 環境変数の設定（Secrets を環境変数として設定）
      - name: Set environment variables
        run: |
          echo "VITE_MVDB_API_KEY=${{ secrets.VITE_MVDB_API_KEY }}" >> $GITHUB_ENV
          echo "VITE_YOUTUBE_API_KEY=${{ secrets.VITE_YOUTUBE_API_KEY }}" >> $GITHUB_ENV

      # 依存関係のインストールとビルド
      - name: Install dependencies and build
        run: |
          npm ci
          npm run build

      # ビルド済みファイルを GitHub Pages にデプロイ
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
